---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: java-web-app-rc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-web-app
  template:
    metadata:
      name: java-web-app-pod
      labels:
        app: java-web-app
    spec:
      containers:
        - name: java-web-app-pod
          image: manashswain7008/maven-web-app
          ports:
            - containerPort : 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-web-app-service
spec:
  type: NodePort
  selector:
    app: java-web-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
...
