---
apiVersion: v1
kind: Pod
metadata:
  name: java-web-app-pod
  namespace: manash-ns
  labels:
    app: java-web-app
spec:
  containers:
    - name: java-web-app-conatiner
      image: manashswain7008/maven-web-app
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-web-app-service
  namespace: manash-ns
spec:
  type: NodePort
  selector:
    app: java-web-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
...
