---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-web-app-rs
spec:
  replicas: 2
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: spring-boot-web-app
  template:
      metadata:
        name: spring-boot-web-app-pod
        labels:
          app: spring-boot-web-app
          type: backend
      spec:
        containers:
          - name: spring-boot-web-app-container
            image: manashswain7008/spring-boot-web-app
            ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-web-app-service
spec:
  type: NodePort
  selector:
    app: spring-boot-web-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
...
